### ISSUE TITLE
Defacto2 Offline

### ISSUE THREAD

**Issue by Defacto2** [Defacto2/defacto2.net#11]
Create an offline Defacto2 file browser that would contain its own self contained SQLite database.
The browser could be programmed in Python or Node.js so it doesn't need compiling and could be cross platform.
Include a precompiled version for Windows users?

All the 'Art & files' hosted on Defacto2 would be included in this Defacto2 Offline distributed package.
All screen captures and thumbnails taken off the site would also be included.
All videos that were recorded for use on the Defacto2 YouTube video MAY also be included or they could be released as a seperate package.
This would be a replacement to the old Defacto2 ISO images that used to be released to the public.

As the package would be quite large it would need to be distributed via BitTorrent and maybe archive.org?

The 'Art & files' stored in the package would need to be renamed into a user friendly format so people could browse and launch them without the need of the Python build file browser.
An idea...
[original file name]_[released-by-group-name]_[year]_[file format]_[category section]_[id].[file extension]
An example...
razor.nfo_razor-1911_1989_text_information_001.nfo

Incorporate http://www.defacto2.net/help/index into the offline file browser and also include as seperate plain text files.

**Comment by bengarrett** [comment]
[Made into a Project](https://github.com/Defacto2/defacto2.net/projects/3)
