### ISSUE TITLE
Add a collection Highlights section.

### ISSUE THREAD

**Issue by Defacto2** [Defacto2/defacto2.net#28]
Create a curated section pointing out and writing about interesting sections of the Defacto2 collection. Cover things such as the early technical ability of the scene, the merging of local scenes into a national scene. Then the joining of USA and Europe. The rise of the ansi art and demoscenes. Highlights of the troll, group and flamewars. Examples of money, crime and arrests. Modern cracktros and music. Electronic magazines. BBSs. FTP sites.

**Comment by bengarrett** [comment]
This idea was replaced by https://defacto2.net/file/index
