### ISSUE TITLE
Wiki controller for group biographies

### ISSUE THREAD

**Issue by Defacto2** [Defacto2/defacto2.net#4]
Create a wiki controller containing group pages using the former biography functionality.

Groups & sites list will detect and trigger a link when there is a biography.

Maybe use a 3rd party Wiki host and tie into their API?
Or use a GitHub Wiki with mark-down?

**Comment by bengarrett** [comment]
[Moved to Projects](https://github.com/Defacto2/defacto2.net/projects/1)
