### ISSUE TITLE
Full file content search

### ISSUE THREAD

**Issue by Defacto2** [Defacto2/defacto2.net#5]
Add full text search using existing database.

Create a new table with text BLOBS.

Each searched file will have it's own UUID and will be linked to files.uuid using one-to-many.

Read plain text files such as an NFO and have all non-standard characters removed such as borders and multiple tab spacing.

**Comment by bengarrett** [comment]
[Moved to projects](https://github.com/Defacto2/defacto2.net/projects/2)
